__description__ = 'Wordpress Two-Factor Authentication Brute-forcer'
__title__ = 'WPBiff'
__version_info__ = ('0', '1', '1')
__version__ = '.'.join(__version_info__)
__author__ = 'Gabor Szathmari'
__credits__ = ['Gabor Szathmari']
__maintainer__ = 'Gabor Szathmari'
__email__ = 'gszathmari@gmail.com'
__status__ = 'beta'
__license__ = 'MIT'
__copyright__ = 'Copyright (c) 2015 Gabor Szathmari'
__website__ = 'http://github.com/gszathmari/wpbiff'
